version: '3.8'

services:
  vagus-app:
    build: .
    ports:
      - "3000:3000"
    # SECURITY: Use environment variables from .env file (never commit credentials)
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    volumes:
      - .:/app
    working_dir: /app
    command: flutter run -d web-server --web-port 3000 --web-hostname 0.0.0.0
