name: vagus_app
description: "A new Flutter project."
publish_to: 'none'

version: 0.9.0+90

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.0
  uuid: ^4.3.3
  intl: ^0.20.2
  csv: ^5.0.2
  path_provider: ^2.1.2
  fl_chart: ^0.66.0
  video_player: ^2.8.3
  just_audio: ^0.9.36
  url_launcher: ^6.2.5
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  mobile_scanner: ^3.5.5
  file_picker: ^6.1.1
  pdf: ^3.11.3
  printing: ^5.12.0
  photo_view: ^0.15.0
  local_auth: ^2.3.0
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.2
  http: ^1.2.0
  collection: ^1.18.0
  crypto: ^3.0.3
  flutter_local_notifications: ^18.0.0
  timezone: ^0.9.2
  lottie: ^2.7.0
  rive: ^0.13.13
  provider: ^6.0.5
  share_plus: ^10.0.2
  equatable: ^2.0.5
  # flutter_webrtc: ^0.11.7  # Temporarily disabled due to compatibility issues
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  app_links: ^6.4.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.2
  mockito: ^5.4.4
  build_runner: ^2.4.9
  flutter_driver:
    sdk: flutter
  test: ^1.25.2

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/foods/
    - assets/branding/vagus_logo_white.png
    - assets/branding/vagus_logo_black.png
    - assets/anim/loading_spinner.json
    - assets/anim/success_check.json
    - assets/anim/empty_box.json
    - assets/anim/typing_dots.json
    - assets/anim/mic_ripple.riv

flutter_native_splash:
  color: "#000000"
  image: assets/branding/vagus_logo_white.png
  android_12:
    color: "#000000"
    image: assets/branding/vagus_logo_white.png
