-- Add ai_generated column to workout_plans table
-- This column flags whether a workout plan was generated by AI

ALTER TABLE workout_plans
ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN NOT NULL DEFAULT false;

-- Create index for filtering AI-generated plans
CREATE INDEX IF NOT EXISTS idx_workout_plans_ai_generated
ON workout_plans(ai_generated);

-- Add comment for documentation
COMMENT ON COLUMN workout_plans.ai_generated IS 'Flag indicating if the workout plan was generated by AI';
