name: Supabase Auto Deploy

on:
  push:
    branches: [ develop, main ]
  workflow_dispatch:

jobs:
  deploy_dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Link dev project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF_DEV }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN_DEV }}

      - name: Push DB migrations (dev)
        run: supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN_DEV }}

      - name: Deploy Edge Functions (dev)
        if: ${{ success() }}
        run: |
          if [ -d supabase/functions ]; then
            for d in supabase/functions/* ; do
              [ -d "$d" ] && supabase functions deploy "$(basename "$d")"
            done
          fi
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN_DEV }}

  deploy_prod:
    if: github.ref == 'refs/heads/main'
    environment: production   # enable manual approval in GitHub Environments for safety
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Link prod project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Push DB migrations (prod)
        run: supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy Edge Functions (prod)
        if: ${{ success() }}
        run: |
          if [ -d supabase/functions ]; then
            for d in supabase/functions/* ; do
              [ -d "$d" ] && supabase functions deploy "$(basename "$d")"
            done
          fi
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
