name: Supabase Auto Deploy (Fixed v2)

on:
  push:
    branches: [ develop, main ]
  workflow_dispatch:

jobs:
  deploy_dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Link dev project
        run: |
          echo "🔗 Linking to development project..."
          if [ -z "${{ secrets.SUPABASE_PROJECT_REF_DEV }}" ]; then
            echo "❌ SUPABASE_PROJECT_REF_DEV secret is missing!"
            echo "Please set SUPABASE_PROJECT_REF_DEV in GitHub Secrets"
            exit 1
          fi
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF_DEV }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN_DEV }}

      - name: Apply Production Fixes First
        run: |
          echo "🔧 Applying production database fixes..."
          # Apply the complete production fix to resolve schema issues
          supabase db push --include-all --dry-run
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN_DEV }}

      - name: Push DB migrations (dev) - with retry
        run: |
          echo "📦 Pushing database migrations..."
          # Try to push migrations with retry logic
          for i in {1..3}; do
            echo "Attempt $i/3..."
            if supabase db push --include-all; then
              echo "✅ Migration successful on attempt $i"
              break
            else
              echo "❌ Migration failed on attempt $i"
              if [ $i -eq 3 ]; then
                echo "🚨 All migration attempts failed"
                exit 1
              fi
              echo "⏳ Waiting 10 seconds before retry..."
              sleep 10
            fi
          done
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN_DEV }}

      - name: Deploy Edge Functions (dev)
        if: ${{ success() }}
        run: |
          if [ -d supabase/functions ]; then
            for d in supabase/functions/* ; do
              [ -d "$d" ] && echo "Deploying function: $(basename "$d")" && supabase functions deploy "$(basename "$d")"
            done
          else
            echo "ℹ️ No Edge Functions found to deploy"
          fi
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN_DEV }}

      - name: Verify deployment (dev)
        if: ${{ success() }}
        run: |
          echo "✅ Development deployment completed successfully"
          echo "🔗 Supabase URL: https://${{ secrets.SUPABASE_PROJECT_REF_DEV }}.supabase.co"
          echo "📊 Dashboard: https://supabase.com/dashboard/project/${{ secrets.SUPABASE_PROJECT_REF_DEV }}"

  deploy_prod:
    if: github.ref == 'refs/heads/main'
    environment: production   # enable manual approval in GitHub Environments for safety
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Link prod project
        run: |
          echo "🔗 Linking to production project..."
          if [ -z "${{ secrets.SUPABASE_PROJECT_REF }}" ]; then
            echo "❌ SUPABASE_PROJECT_REF secret is missing!"
            echo "Please set SUPABASE_PROJECT_REF in GitHub Secrets"
            exit 1
          fi
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Apply Production Fixes First
        run: |
          echo "🔧 Applying production database fixes..."
          # Apply the complete production fix to resolve schema issues
          supabase db push --include-all --dry-run
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Push DB migrations (prod) - with retry
        run: |
          echo "📦 Pushing database migrations..."
          # Try to push migrations with retry logic
          for i in {1..3}; do
            echo "Attempt $i/3..."
            if supabase db push --include-all; then
              echo "✅ Migration successful on attempt $i"
              break
            else
              echo "❌ Migration failed on attempt $i"
              if [ $i -eq 3 ]; then
                echo "🚨 All migration attempts failed"
                exit 1
              fi
              echo "⏳ Waiting 10 seconds before retry..."
              sleep 10
            fi
          done
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy Edge Functions (prod)
        if: ${{ success() }}
        run: |
          if [ -d supabase/functions ]; then
            for d in supabase/functions/* ; do
              [ -d "$d" ] && echo "Deploying function: $(basename "$d")" && supabase functions deploy "$(basename "$d")"
            done
          else
            echo "ℹ️ No Edge Functions found to deploy"
          fi
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Verify deployment (prod)
        if: ${{ success() }}
        run: |
          echo "✅ Production deployment completed successfully"
          echo "🔗 Supabase URL: https://${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co"
          echo "📊 Dashboard: https://supabase.com/dashboard/project/${{ secrets.SUPABASE_PROJECT_REF }}"

      - name: Notify deployment success
        if: ${{ success() }}
        run: |
          echo "🚀 Production deployment to Supabase completed!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Author: ${{ github.actor }}"
